import catalogue from "@/lib/aws-icons/catalogue.json" with { type: "json" }

/**
 * The AWS service icons available to the draw tool.
 *
 * `catalogue.json` is generated by `scripts/build-aws-icons.ts` from the
 * `aws-icons` dependency and committed, because it is metadata rather than
 * artwork — typecheck and lint have to work without running the script. The SVGs
 * themselves are copied into a gitignored `public/aws-icons/` at build time.
 *
 * Shared by client and server, so no server-only imports.
 */

type AwsIcon = {
  slug: string
  name: string
}

const AWS_ICONS: readonly AwsIcon[] = catalogue

const awsIconsBySlug = new Map(AWS_ICONS.map(icon => [icon.slug, icon]))

const awsIconUrl = (slug: string): string => `/aws-icons/${slug}.svg`

const awsIconName = (slug: string): string => awsIconsBySlug.get(slug)?.name ?? slug

/**
 * Every term must match, so extra words narrow rather than widen — the same rule
 * the tool directory and the drawings gallery use.
 *
 * Matches the slug as well as the name so that "ec2" finds "Amazon EC2" even
 * though the display name spaces it differently.
 */
const matchesAwsIcon = (icon: AwsIcon, query: string): boolean => {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean)

  if (terms.length === 0) {
    return true
  }

  const haystack = `${icon.name} ${icon.slug}`.toLowerCase()

  return terms.every(term => haystack.includes(term))
}

export { AWS_ICONS, awsIconName, awsIconUrl, matchesAwsIcon }
export type { AwsIcon }
