import catalogue from "@/lib/aws-icons/catalogue.json" with { type: "json" }

/**
 * The AWS service icons available to the draw tool.
 *
 * `catalogue.json` is generated by `scripts/build-aws-icons.ts` from the
 * `aws-icons` dependency and committed, because it is metadata rather than
 * artwork — typecheck and lint have to work without running the script. The SVGs
 * themselves are copied into a gitignored `public/aws-icons/` at build time.
 *
 * Everything the package ships is included, unlike the curated Cloudflare
 * catalogue: `aws-icons` contains architecture icons and nothing else, so there
 * is nothing to filter out.
 *
 * Shared by client and server, so no server-only imports.
 */

type AwsIcon = {
  slug: string
  name: string
}

const AWS_ICONS: readonly AwsIcon[] = catalogue

const awsIconUrl = (slug: string): string => `/aws-icons/${slug}.svg`

export { AWS_ICONS, awsIconUrl }
export type { AwsIcon }
