import catalogue from "@/lib/cloudflare-icons/catalogue.json" with { type: "json" }

/**
 * The Cloudflare product icons available to the draw tool.
 *
 * `catalogue.json` is generated by `scripts/build-cloudflare-icons.tsx` from the
 * allowlist in `products.json` and committed, because it is metadata rather than
 * artwork — typecheck and lint have to work without running the script. The SVGs
 * themselves are rendered into a gitignored `public/cloudflare-icons/` at build
 * time.
 *
 * Unlike the AWS catalogue this is a curated subset rather than everything the
 * upstream package offers: `@cloudflare/component-icon` is a general interface
 * kit, so taking all of it would put scrollbar carets and other companies' logos
 * in the picker. See `docs/adr/0003-cloudflare-icons.md`.
 *
 * Shared by client and server, so no server-only imports.
 */

type CloudflareIcon = {
  slug: string
  name: string
}

const CLOUDFLARE_ICONS: readonly CloudflareIcon[] = catalogue

const cloudflareIconUrl = (slug: string): string => `/cloudflare-icons/${slug}.svg`

export { CLOUDFLARE_ICONS, cloudflareIconUrl }
export type { CloudflareIcon }
